[target.x86_64-pc-windows-msvc]
linker = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/link.exe"
rustflags = [
  "-L",
  "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.26100.0/um/x64",
  "-L",
  "C:/Program Files (x86)/Windows Kits/10/Lib/10.0.26100.0/ucrt/x64",
  "-L",
  "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/lib/x64",
]

[env]
VCINSTALLDIR = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/"
CC = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/cl.exe"
CXX = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/cl.exe"
AR = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64/lib.exe"
PATH = { value = "C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64;E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64", relative = false }
Path = { value = "C:/Program Files (x86)/Windows Kits/10/bin/10.0.26100.0/x64;E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/bin/Hostx64/x64", relative = false }
INCLUDE = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/include;C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/ucrt;C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/shared;C:/Program Files (x86)/Windows Kits/10/Include/10.0.26100.0/um"
LIB = "E:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.51.36231/lib/x64;C:/Program Files (x86)/Windows Kits/10/Lib/10.0.26100.0/ucrt/x64;C:/Program Files (x86)/Windows Kits/10/Lib/10.0.26100.0/um/x64"
